# Generated by Django 4.1.7 on 2023-03-29 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_product_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='wanted_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.product'),
        ),
    ]
