# Generated by Django 4.1.7 on 2023-03-29 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_bids_wanted_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bids',
        ),
    ]
