# Generated by Django 4.1.7 on 2023-03-29 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_bids'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bids',
        ),
    ]
